### ISSUE TITLE
Mkdir on Upload

### ISSUE THREAD

**Issue by seanwu1105** [satackey/action-google-drive#12]
Currently, the directory of `upload-to` property need to be created manually before the action runs to avoid the following error:

```
skicka: /path/to/upload: not found
```

It would be really convenient to create the target directory before the upload.

```
skicka mkdir -p /path/to/upload
```

By doing so, this action can be easily integrated with variables with simple expression. For example,

``` yml
- name: Upload files to Google Drive
  uses: satackey/action-google-drive@v1
  with:
    skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
    google-client-id: ${{ secrets.SKICKA_GOOGLE_CLIENT_ID }}
    google-client-secret: ${{ secrets.SKICKA_GOOGLE_CLIENT_SECRET }}
    upload-from: ./app/build/outputs/apk/
    upload-to: /my-app/apk/${{ steps.extract_version.outputs.appVersionName }}/
```

The expression, `${{ steps.extract_version.outputs.appVersionName }}`, might be changed every time the action runs.
