### ISSUE TITLE
downloading a file by specifying the owner

### ISSUE THREAD

**Issue by ryan5500** [satackey/action-google-drive#17]
# problem

When I download a folder from google drive using this action, the file owner is `root:root`.

I am running a test program in CI, which place new files in a downloaded folder by this action.
However, when program try to place new files, I've got Permission Denied because the owner of the downloaded folder is root:root.

As a workaround, I have added a process to change the owner of the folder after downloading the folder by action.
An example is shown below.

```yaml
name: Test
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Download test data from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: /test-data
          download-to: ${{ github.workspace }}/tests/files/test-data/
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: chown testdata dir (because satackey/action-google-drive@v1 downloads files as root owner)
        run: sudo chown -R runner:docker ${{ github.workspace }}/tests/files/test-data
```

# suggestion

I would like to achieve simplicity in the description, preferably by specifying the user in the action.

For example, can we use the following option?

```yaml
      - name: Download test data from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: /test-data
          download-to: ${{ github.workspace }}/tests/files/test-data/
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          user: runner # added
          group: docker # added
```
